/**
 * SAAYA Backend Multi-Language Music Catalog
 * Strictly maintained on the backend server with verified YouTube IDs,
 * rich artist lore, composition backstories, and time-of-day affinities.
 */

export const MUSIC_CATALOG = [
  // ── ENGLISH ─────────────────────────────────────────────────────────────
  {
    id: 'track-en-1',
    title: 'The Night We Met',
    artist: 'Lord Huron',
    language: 'English',
    languageCode: 'en-US',
    meta: 'INDIE FOLK · 2015 · MIDNIGHT ECHOES',
    youtubeId: 'KtlgYxa6BMU',
    lore: 'Frontman Ben Schneider wrote this after meditating on the phantom weight of memories and love lost to time, recording the vocals through vintage analog tape to capture that hollow, haunting warmth.',
    artistBackground: 'Formed by Michigan songwriter Ben Schneider, Lord Huron crafts cinematic folk journeys inspired by campfires, desert horizons, and mid-century noir.',
    timeSuitability: ['evening', 'after-dark'],
    art: 'radial-gradient(circle at 68% 28%, #e7d7be 0 7%, transparent 24%), radial-gradient(ellipse at 40% 60%, #9b4d35 0 12%, transparent 45%), conic-gradient(from 140deg, #171b24, #6d2d28, #d08a62, #20252f, #171b24)',
    core: '#efb37b',
    glow: 'rgba(172,82,51,.34)',
    rotate: '-22deg'
  },
  {
    id: 'track-en-2',
    title: 'Sundown',
    artist: 'Lana Del Rey',
    language: 'English',
    languageCode: 'en-US',
    meta: 'ALT POP · 2019 · VELVET HOUR',
    youtubeId: 'nVjsGKrE6E8',
    lore: 'An evocative acoustic piece blending faded Hollywood glamour with the bittersweet sting of summer evenings giving way to twilight.',
    artistBackground: 'Lana Del Rey defined an entire generation of cinematic baroque-pop, chronicling tragic romance, coastal melancholy, and Americana dreamscapes.',
    timeSuitability: ['golden-hour', 'evening'],
    art: 'radial-gradient(circle at 56% 70%, #f4c08c 0 8%, transparent 26%), radial-gradient(ellipse at 25% 30%, #783a29 0 12%, transparent 46%), conic-gradient(from 20deg, #26161f, #ad624a, #deaa69, #53333c, #26161f)',
    core: '#e4a06b',
    glow: 'rgba(177,92,58,.3)',
    rotate: '-8deg'
  },
  {
    id: 'track-en-3',
    title: 'A Walk',
    artist: 'Tycho',
    language: 'English',
    languageCode: 'en-US',
    meta: 'AMBIENT ELECTRONIC · 2014 · OPEN SKIES',
    youtubeId: 'mehLx_Fjv_c',
    lore: 'Constructed layer by layer in Scott Hansen’s San Francisco studio using warm analog synths and tape delays, designed to evoke the sensation of walking out into crisp morning air under wide open skies.',
    artistBackground: 'Tycho is the ambient audio-visual project of designer and musician Scott Hansen, legendary for balancing organic warmth with electronic precision.',
    timeSuitability: ['morning', 'daylight'],
    art: 'radial-gradient(circle at 60% 36%, #c3d9d0 0 7%, transparent 25%), radial-gradient(ellipse at 34% 70%, #3c7370 0 15%, transparent 46%), conic-gradient(from 120deg, #14252c, #4c9993, #b2d4c1, #315162, #14252c)',
    core: '#b9dfd1',
    glow: 'rgba(76,153,147,.32)',
    rotate: '14deg'
  },
  {
    id: 'track-en-4',
    title: 'Apocalypse',
    artist: 'Cigarettes After Sex',
    language: 'English',
    languageCode: 'en-US',
    meta: 'SLOWCORE · 2017 · NOCTURNE',
    youtubeId: 'sElE_BfQ67s',
    lore: 'Recorded in a cavernous stairwell in Brooklyn with minimal microphones to let the natural acoustic reverb envelop Greg Gonzalez’s whispered confession of love during the end of the world.',
    artistBackground: 'Led by Greg Gonzalez, the Texas-born dream-pop outfit is celebrated worldwide for their monochrome aesthetics and hypnotic slowcore sound.',
    timeSuitability: ['evening', 'after-dark'],
    art: 'radial-gradient(circle at 45% 35%, #f0f0f0 0 6%, transparent 20%), radial-gradient(ellipse at 50% 65%, #3a3d40 0 16%, transparent 48%), conic-gradient(from 210deg, #0d0e12, #30333b, #8a8d98, #181a20, #0d0e12)',
    core: '#c9ccd6',
    glow: 'rgba(138,141,152,.28)',
    rotate: '-15deg'
  },
  {
    id: 'track-en-5',
    title: 'Another Love',
    artist: 'Tom Odell',
    language: 'English',
    languageCode: 'en-US',
    meta: 'INDIE POP · 2013 · NOSTALGIC',
    youtubeId: 'MwpMEbgC7DA',
    lore: 'Composed on an upright piano when Odell was just 21, capturing the exhausting struggle of wanting to love someone completely when past heartbreaks have left your emotional reserves depleted.',
    artistBackground: 'British singer-songwriter Tom Odell rose from open mics in Brighton to global acclaim with his raw vocal vulnerability and poignant piano arrangements.',
    timeSuitability: ['golden-hour', 'evening'],
    art: 'radial-gradient(circle at 35% 31%, #e2eef1 0 4%, transparent 18%), radial-gradient(ellipse at 62% 66%, #8c93bb 0 10%, transparent 42%), conic-gradient(from 200deg, #2c2638, #b78a9e, #d8d7bf, #555a84, #2c2638)',
    core: '#e2ded0',
    glow: 'rgba(146,141,180,.3)',
    rotate: '28deg'
  },

  // ── HINDI ───────────────────────────────────────────────────────────────
  {
    id: 'track-hi-1',
    title: 'Kasoor',
    artist: 'Prateek Kuhad',
    language: 'Hindi',
    languageCode: 'hi-IN',
    meta: 'HINDI INDIE · 2020 · WARM EMBER',
    youtubeId: 'BmUe3-sfr7E',
    lore: 'Written around tender acoustic guitar fingerpicking and an intimate vocal delivery that feels like a whispered conversation in a quiet living room.',
    artistBackground: 'Delhi and New York-based Prateek Kuhad pioneered the modern Indian independent singer-songwriter wave, acclaimed for his deeply sincere, minimalist love songs.',
    timeSuitability: ['morning', 'evening', 'after-dark'],
    art: 'radial-gradient(circle at 72% 35%, #ffd194 0 9%, transparent 28%), radial-gradient(ellipse at 38% 65%, #d16b47 0 15%, transparent 50%), conic-gradient(from 45deg, #1f1412, #8c3f2d, #f5a26c, #3b1e1b, #1f1412)',
    core: '#f5a26c',
    glow: 'rgba(214,107,71,.35)',
    rotate: '18deg'
  },
  {
    id: 'track-hi-2',
    title: 'Baarishein',
    artist: 'Anuv Jain',
    language: 'Hindi',
    languageCode: 'hi-IN',
    meta: 'ACOUSTIC POETRY · 2018 · MIDNIGHT RAIN',
    youtubeId: 'PJWemSzExXs',
    lore: 'Composed on a simple ukulele and acoustic guitar during a quiet monsoon afternoon, drawing on the gentle sound of rainfall as an uncredited second instrument.',
    artistBackground: 'Anuv Jain gained cult adoration across South Asia for his poetic storytelling, heartfelt baritone, and evocative acoustic ballads.',
    timeSuitability: ['daylight', 'golden-hour', 'after-dark'],
    art: 'radial-gradient(circle at 30% 40%, #b8e2f2 0 8%, transparent 25%), radial-gradient(ellipse at 65% 60%, #4a7c92 0 16%, transparent 48%), conic-gradient(from 190deg, #0e1c24, #27566b, #8bc3db, #19323f, #0e1c24)',
    core: '#8bc3db',
    glow: 'rgba(74,124,146,.32)',
    rotate: '-12deg'
  },
  {
    id: 'track-hi-3',
    title: 'Choo Lo',
    artist: 'The Local Train',
    language: 'Hindi',
    languageCode: 'hi-IN',
    meta: 'HINDI ROCK · 2015 · ECHOES OF PASSAGE',
    youtubeId: 'sFMRqxCexDk',
    lore: 'Features sweeping electric guitars and Raman Negi’s impassioned vocals singing about holding onto fleeting moments before paths diverge forever.',
    artistBackground: 'The Local Train emerged from Chandigarh and Delhi as modern trailblazers of Hindi indie rock, known for poetic Hindi lyrics set to soaring guitar anthems.',
    timeSuitability: ['daylight', 'golden-hour'],
    art: 'radial-gradient(circle at 50% 30%, #f7d6a5 0 10%, transparent 30%), radial-gradient(ellipse at 50% 70%, #9e4b33 0 18%, transparent 52%), conic-gradient(from 310deg, #1f1717, #7a2e1d, #d67a58, #361f1d, #1f1717)',
    core: '#e8906c',
    glow: 'rgba(158,75,51,.34)',
    rotate: '24deg'
  },
  {
    id: 'track-hi-4',
    title: 'Husn',
    artist: 'Anuv Jain',
    language: 'Hindi',
    languageCode: 'hi-IN',
    meta: 'INDIE SOUL · 2023 · DEEP LONGING',
    youtubeId: 'gJLVTKhTnog',
    lore: 'Explores modern situationships and unspoken love through delicate piano chords, capturing the vulnerability of being loved in fragments rather than completely.',
    artistBackground: 'Anuv Jain cemented his status as the poetic voice of a generation with this introspective masterwork.',
    timeSuitability: ['evening', 'after-dark'],
    art: 'radial-gradient(circle at 62% 38%, #fce2db 0 8%, transparent 26%), radial-gradient(ellipse at 42% 64%, #8c4c5a 0 16%, transparent 48%), conic-gradient(from 160deg, #1f1216, #6b2d3d, #c27b8e, #2d1820, #1f1216)',
    core: '#c27b8e',
    glow: 'rgba(140,76,90,.34)',
    rotate: '-16deg'
  },

  // ── JAPANESE ────────────────────────────────────────────────────────────
  {
    id: 'track-ja-1',
    title: 'Stay With Me (真夜中のドア)',
    artist: 'Miki Matsubara',
    language: 'Japanese',
    languageCode: 'ja-JP',
    meta: 'CITY POP · 1979 · NEON METROPOLIS',
    youtubeId: 'nuU2YHtxMik',
    lore: 'Composed by Tetsuji Hayashi and recorded in Tokyo in 1979, the track captures the sparkling night optimism and subtle melancholy of midnight city life in Japan.',
    artistBackground: 'Miki Matsubara was just 19 when she recorded this track, which four decades later became the global anthem for the worldwide Japanese City Pop renaissance.',
    timeSuitability: ['golden-hour', 'evening', 'after-dark'],
    art: 'radial-gradient(circle at 65% 25%, #fce38a 0 8%, transparent 26%), radial-gradient(ellipse at 35% 68%, #f38181 0 16%, transparent 46%), conic-gradient(from 160deg, #241424, #953b64, #ea728c, #3d1b38, #241424)',
    core: '#f38181',
    glow: 'rgba(234,114,140,.36)',
    rotate: '-20deg'
  },
  {
    id: 'track-ja-2',
    title: 'Shinunoga E-Wa (死ぬのがいいわ)',
    artist: 'Fujii Kaze',
    language: 'Japanese',
    languageCode: 'ja-JP',
    meta: 'J-POP / SOUL · 2020 · HAUNTING GROOVE',
    youtubeId: 'dawrQnvwMTY',
    lore: 'Blends urban jazz keys with trap-influenced percussion and Japanese folk scales, singing about spiritual dedication and refusing to live without one’s core truth.',
    artistBackground: 'Born in Okayama, Fujii Kaze began uploading piano improvisations as a teenager and has evolved into one of Japan’s most genre-defying musical prodigies.',
    timeSuitability: ['daylight', 'evening', 'after-dark'],
    art: 'radial-gradient(circle at 40% 30%, #ffd3b6 0 7%, transparent 22%), radial-gradient(ellipse at 60% 65%, #6a2c70 0 15%, transparent 48%), conic-gradient(from 260deg, #180d1e, #581845, #c70039, #290f2b, #180d1e)',
    core: '#e87588',
    glow: 'rgba(199,0,57,.32)',
    rotate: '16deg'
  },
  {
    id: 'track-ja-3',
    title: 'Sparkle',
    artist: 'RADWIMPS',
    language: 'Japanese',
    languageCode: 'ja-JP',
    meta: 'NEO-ORCHESTRAL · 2016 · TWILIGHT HORIZON',
    youtubeId: 'a2GujJZfXpg',
    lore: 'Written for Makoto Shinkai’s anime masterpiece "Your Name", featuring cascading piano arpeggios that build into a breathless orchestral climax about finding love across time and memories.',
    artistBackground: 'Fronted by Yojiro Noda, RADWIMPS is one of Japan’s most versatile rock and orchestral ensembles, famous for their emotionally staggering cinematic scores.',
    timeSuitability: ['morning', 'golden-hour'],
    art: 'radial-gradient(circle at 55% 40%, #e0f7fa 0 8%, transparent 25%), radial-gradient(ellipse at 45% 65%, #00838f 0 14%, transparent 46%), conic-gradient(from 90deg, #091921, #006064, #4dd0e1, #102a36, #091921)',
    core: '#4dd0e1',
    glow: 'rgba(0,131,143,.35)',
    rotate: '-10deg'
  },

  // ── SPANISH ─────────────────────────────────────────────────────────────
  {
    id: 'track-es-1',
    title: 'Lover Is a Day',
    artist: 'Cuco',
    language: 'Spanish / English',
    languageCode: 'es-ES',
    meta: 'CHICANO LOFI · 2016 · DREAMSCAPE',
    youtubeId: 'k238XpMMn38',
    lore: 'Self-produced in his childhood bedroom in Hawthorne, California, with warped vintage synths, sleepy trumpet solos, and bilingual lyrics capturing the haze of youthful romance.',
    artistBackground: 'Mexican-American multi-instrumentalist Cuco popularized bedroom pop for a bilingual generation, fusing classic bossa nova chord changes with modern lofi hip-hop.',
    timeSuitability: ['daylight', 'golden-hour', 'after-dark'],
    art: 'radial-gradient(circle at 62% 33%, #ffd8be 0 7%, transparent 24%), radial-gradient(ellipse at 38% 64%, #805b87 0 15%, transparent 45%), conic-gradient(from 135deg, #1f1627, #6c4b78, #caa8d4, #2a1b32, #1f1627)',
    core: '#c497cf',
    glow: 'rgba(128,91,135,.32)',
    rotate: '22deg'
  },
  {
    id: 'track-es-2',
    title: 'Hasta la Raíz',
    artist: 'Natalia Lafourcade',
    language: 'Spanish',
    languageCode: 'es-ES',
    meta: 'FOLK LATINO · 2015 · EARTH & MEMORY',
    youtubeId: 'IKmPci5VXz0',
    lore: 'Inspired by Lafourcade’s travels across Mexico, celebrating ancestral roots, huapango rhythms, and the idea that love stays rooted in your spirit no matter how far you wander.',
    artistBackground: 'Natalia Lafourcade is a revered Mexican musical icon and multi-Grammy winner whose work honors the deep folkloric roots of Latin American music.',
    timeSuitability: ['morning', 'daylight', 'golden-hour'],
    art: 'radial-gradient(circle at 45% 30%, #fbe3b5 0 9%, transparent 27%), radial-gradient(ellipse at 55% 70%, #945d3e 0 16%, transparent 48%), conic-gradient(from 75deg, #211612, #6b3e26, #cfa06b, #301f18, #211612)',
    core: '#d9a775',
    glow: 'rgba(148,93,62,.33)',
    rotate: '-14deg'
  },

  // ── FRENCH ──────────────────────────────────────────────────────────────
  {
    id: 'track-fr-1',
    title: 'Amour Plastique',
    artist: 'Videoclub',
    language: 'French',
    languageCode: 'fr-FR',
    meta: 'FRENCH SYNTHPOP · 2018 · RETRO ROMANCE',
    youtubeId: '5NjJLFI_oYs',
    lore: 'A glowing love letter to 1980s French electro-pop, written when Adèle Castillon and Matthieu Reynaud were teenage sweethearts recording in Nantes with vintage synthesizers.',
    artistBackground: 'French duo Videoclub took Europe by storm with their sun-drenched, retro VHS aesthetics and sweet romantic pop hooks.',
    timeSuitability: ['daylight', 'golden-hour'],
    art: 'radial-gradient(circle at 70% 32%, #ffb6b9 0 8%, transparent 25%), radial-gradient(ellipse at 32% 64%, #6155a6 0 15%, transparent 46%), conic-gradient(from 220deg, #171427, #544376, #f3a683, #231d36, #171427)',
    core: '#f8a5c2',
    glow: 'rgba(97,85,166,.34)',
    rotate: '28deg'
  },
  {
    id: 'track-fr-2',
    title: 'Dernière Danse',
    artist: 'Indila',
    language: 'French',
    languageCode: 'fr-FR',
    meta: 'CHANSON NOIR · 2013 · PARISIAN WIND',
    youtubeId: 'K5KAc5CoCuk',
    lore: 'Orchestrated with sweeping Mediterranean strings and dramatic pop percussion, depicting a lonely woman dancing through the cold Parisian wind to banish the heartache of loss.',
    artistBackground: 'Indila captivated global audiences with her distinctive fusion of French chanson, Algerian rhythms, and cinematic symphonic pop.',
    timeSuitability: ['evening', 'after-dark'],
    art: 'radial-gradient(circle at 35% 35%, #e8d0a9 0 6%, transparent 22%), radial-gradient(ellipse at 65% 65%, #4a4a58 0 14%, transparent 46%), conic-gradient(from 330deg, #14141a, #433948, #9a8c9e, #1e1d26, #14141a)',
    core: '#b5a7ba',
    glow: 'rgba(154,140,158,.3)',
    rotate: '-25deg'
  },

  // ── KOREAN ──────────────────────────────────────────────────────────────
  {
    id: 'track-ko-1',
    title: 'Through the Night (밤편지)',
    artist: 'IU (아이유)',
    language: 'Korean',
    languageCode: 'ko-KR',
    meta: 'K-FOLK ACOUSTIC · 2017 · WHISPERING SHORE',
    youtubeId: 'BzYnNdJhZQw',
    lore: 'Written by IU late at night during a period of insomnia, penned as a gentle letter wishing a peaceful, dreamless sleep for someone she deeply cares for from afar.',
    artistBackground: 'IU is South Korea’s preeminent singer-songwriter, beloved for her emotive literary lyricism, acoustic warmth, and angelic vocal clarity.',
    timeSuitability: ['evening', 'after-dark'],
    art: 'radial-gradient(circle at 60% 30%, #e6dfd5 0 8%, transparent 24%), radial-gradient(ellipse at 35% 68%, #5a6672 0 15%, transparent 45%), conic-gradient(from 110deg, #161c22, #41505c, #9eb3c2, #242d35, #161c22)',
    core: '#adc3d1',
    glow: 'rgba(90,102,114,.3)',
    rotate: '12deg'
  },
  {
    id: 'track-ko-2',
    title: 'instagram',
    artist: 'DEAN',
    language: 'Korean',
    languageCode: 'ko-KR',
    meta: 'K-R&B / LOFI · 2017 · BLUE SCREEN BLUES',
    youtubeId: 'wKyMIrBClYw',
    lore: 'Explores the modern epidemic of scrolling through social media late at night, feeling isolated while watching the curated lives of strangers in the dark.',
    artistBackground: 'DEAN is a visionary South Korean R&B artist and producer who seamlessly merges modern Seoul groove with melancholic alt-R&B sensibilities.',
    timeSuitability: ['evening', 'after-dark'],
    art: 'radial-gradient(circle at 40% 38%, #c5d0e6 0 7%, transparent 23%), radial-gradient(ellipse at 68% 62%, #384259 0 16%, transparent 48%), conic-gradient(from 200deg, #0e121a, #26334a, #70819e, #171d29, #0e121a)',
    core: '#8b9bb4',
    glow: 'rgba(56,66,89,.35)',
    rotate: '-18deg'
  },

  // ── MARATHI ─────────────────────────────────────────────────────────────
  {
    id: 'track-mr-1',
    title: 'Yad Lagla',
    artist: 'Ajay-Atul',
    language: 'Marathi',
    languageCode: 'mr-IN',
    meta: 'ORCHESTRAL MARATHI · 2016 · CINEMATIC LONGING',
    youtubeId: 'VmU1ZsXUbG0',
    lore: 'Recorded with a 66-piece live orchestra at Sony Scoring Stage in Los Angeles, this was the first Indian film song recorded in Hollywood, capturing the dizzying euphoria of first love.',
    artistBackground: 'Brothers Ajay and Atul Gogavale are legendary composer-arrangers who elevated Marathi cinema music to grand symphonic and global standards.',
    timeSuitability: ['morning', 'golden-hour'],
    art: 'radial-gradient(circle at 65% 30%, #ffeaa7 0 8%, transparent 26%), radial-gradient(ellipse at 35% 65%, #d63031 0 15%, transparent 48%), conic-gradient(from 50deg, #2b1111, #842324, #e17055, #3d1717, #2b1111)',
    core: '#e17055',
    glow: 'rgba(214,48,49,.35)',
    rotate: '20deg'
  },
  {
    id: 'track-mr-2',
    title: 'Radha Hi Bawari',
    artist: 'Swapnil Bandodkar',
    language: 'Marathi',
    languageCode: 'mr-IN',
    meta: 'BHAVGEET · 2005 · MOONLIT DEVOTION',
    youtubeId: 'N2foIIJIPzI',
    lore: 'A timeless romantic bhavgeet featuring classical flute melodies, expressing the divine longing and surrender of Radha awaiting Krishna under moonlit skies.',
    artistBackground: 'Swapnil Bandodkar is an acclaimed Marathi playback vocalist renowned for his soulful tone and mastery over semi-classical bhavgeet compositions.',
    timeSuitability: ['evening', 'after-dark'],
    art: 'radial-gradient(circle at 45% 35%, #e3f2fd 0 8%, transparent 25%), radial-gradient(ellipse at 55% 65%, #5c6bc0 0 14%, transparent 45%), conic-gradient(from 180deg, #151928, #3949ab, #9fa8da, #1f253d, #151928)',
    core: '#9fa8da',
    glow: 'rgba(92,107,192,.32)',
    rotate: '-14deg'
  },

  // ── GERMAN / NORDIC ─────────────────────────────────────────────────────
  {
    id: 'track-de-1',
    title: 'Stolen Dance',
    artist: 'Milky Chance',
    language: 'German / English',
    languageCode: 'de-DE',
    meta: 'FOLKTRONICA · 2013 · DUSK GUITAR',
    youtubeId: 'iX-QaNzd-0Y',
    lore: 'Self-recorded in Clemens Rehbein’s childhood bedroom in Kassel, Germany, combining relaxed reggae strumming, indie folk guitar, and minimalist digital beats.',
    artistBackground: 'German duo Milky Chance gained international stardom by defining the breezy, sun-dappled folktronica genre.',
    timeSuitability: ['daylight', 'golden-hour'],
    art: 'radial-gradient(circle at 50% 30%, #e8d8c8 0 8%, transparent 25%), radial-gradient(ellipse at 50% 68%, #785a46 0 15%, transparent 46%), conic-gradient(from 290deg, #1f1a16, #5c4331, #b59275, #2e241e, #1f1a16)',
    core: '#c4a488',
    glow: 'rgba(120,90,70,.32)',
    rotate: '15deg'
  },

  // ── URDU / PAKISTANI INDIE ──────────────────────────────────────────────
  {
    id: 'track-ur-1',
    title: 'Iraaday',
    artist: 'Abdul Hannan & Rovalio',
    language: 'Urdu',
    languageCode: 'ur-PK',
    meta: 'URDU INDIE · 2022 · BEDROOM CONFESSION',
    youtubeId: 'Qwm6BSGrOq0',
    lore: 'Penned in a quiet room in Lahore with gentle guitar arpeggios, capturing the tender vulnerability of confessing love with no pretense.',
    artistBackground: 'Abdul Hannan emerged from Pakistan as a viral indie sensation whose delicate voice and honest songwriting resonated globally.',
    timeSuitability: ['evening', 'after-dark', 'golden-hour'],
    art: 'radial-gradient(circle at 65% 35%, #fde2e4 0 8%, transparent 26%), radial-gradient(ellipse at 35% 65%, #9b5de5 0 15%, transparent 48%), conic-gradient(from 140deg, #1d1128, #5c2c90, #c77dff, #241433, #1d1128)',
    core: '#c77dff',
    glow: 'rgba(155,93,229,.35)',
    rotate: '-18deg'
  },
  {
    id: 'track-ur-2',
    title: 'Bikhra',
    artist: 'Abdul Hannan & Rovalio',
    language: 'Urdu',
    languageCode: 'ur-PK',
    meta: 'URDU INDIE · 2022 · VELVET NOSTALGIA',
    youtubeId: '7enmkIJPAdo',
    lore: 'Combines lofi percussion with melancholic Urdu verses, exploring feelings of emotional fragmentation after parting ways.',
    artistBackground: 'Collaborating with producer Rovalio, Hannan established a signature sound of warm acoustic introspection for South Asian youth.',
    timeSuitability: ['evening', 'after-dark'],
    art: 'radial-gradient(circle at 40% 30%, #e0c3fc 0 8%, transparent 25%), radial-gradient(ellipse at 60% 68%, #480ca8 0 16%, transparent 50%), conic-gradient(from 220deg, #100b20, #3a0ca3, #8a5df5, #1c0e3d, #100b20)',
    core: '#8a5df5',
    glow: 'rgba(72,12,168,.34)',
    rotate: '16deg'
  },

  // ── PUNJABI SOUL ────────────────────────────────────────────────────────
  {
    id: 'track-pa-1',
    title: 'Faasle',
    artist: 'Aditya Rikhari',
    language: 'Punjabi / Hindi',
    languageCode: 'pa-IN',
    meta: 'PUNJABI INDIE · 2021 · BITTERSWEET DRIFT',
    youtubeId: 'fhytM4I4Q94',
    lore: 'Written around a driving acoustic strum and raw baritone vocals, exploring unbridgeable emotional distance between two people who still care.',
    artistBackground: 'Aditya Rikhari pioneered an emotional acoustic indie style in North India, connecting indie intimacy with traditional Punjabi longing.',
    timeSuitability: ['golden-hour', 'evening'],
    art: 'radial-gradient(circle at 55% 30%, #ffd6a5 0 9%, transparent 27%), radial-gradient(ellipse at 45% 70%, #d00000 0 16%, transparent 48%), conic-gradient(from 80deg, #240b0b, #9d0208, #ff85a1, #330c12, #240b0b)',
    core: '#ff85a1',
    glow: 'rgba(208,0,0,.35)',
    rotate: '-12deg'
  },

  // ── TAMIL INDIE ─────────────────────────────────────────────────────────
  {
    id: 'track-ta-1',
    title: 'Nee Kavithaigala',
    artist: 'Pradeep Kumar',
    language: 'Tamil',
    languageCode: 'ta-IN',
    meta: 'TAMIL ACOUSTIC · 2017 · COASTAL BREEZE',
    youtubeId: 'pVkDZueTBpY',
    lore: 'Composed by Dhibu Ninan Thomas with Pradeep Kumar’s soulful, feather-light vocals, celebrating the poetic wonder of falling in love like a verse come to life.',
    artistBackground: 'Pradeep Kumar is a celebrated Indian playback singer and slide guitarist trained in Carnatic classical traditions, acclaimed for his emotive acoustic compositions.',
    timeSuitability: ['morning', 'daylight', 'golden-hour'],
    art: 'radial-gradient(circle at 60% 32%, #d8f3dc 0 8%, transparent 25%), radial-gradient(ellipse at 38% 66%, #2d6a4f 0 15%, transparent 46%), conic-gradient(from 160deg, #081c15, #1b4332, #74c69d, #0d281e, #081c15)',
    core: '#74c69d',
    glow: 'rgba(45,106,79,.33)',
    rotate: '14deg'
  },

  // ── BRAZILIAN / PORTUGUESE ──────────────────────────────────────────────
  {
    id: 'track-pt-1',
    title: 'Tuyo',
    artist: 'Rodrigo Amarante',
    language: 'Portuguese / Spanish',
    languageCode: 'pt-BR',
    meta: 'BOLERO NOIR · 2015 · VELVET SHADOWS',
    youtubeId: 'zNPXnAVyAUA',
    lore: 'Inspired by the boleros Amarante’s mother listened to during his childhood in Rio de Janeiro, recorded with an old nylon guitar and an intimate, breathy croon.',
    artistBackground: 'Rio-born Rodrigo Amarante was a core member of indie rock band Los Hermanos and Little Joy before writing this globally acclaimed cinematic bolero.',
    timeSuitability: ['evening', 'after-dark'],
    art: 'radial-gradient(circle at 50% 35%, #ffccd5 0 7%, transparent 24%), radial-gradient(ellipse at 50% 68%, #590d22 0 16%, transparent 48%), conic-gradient(from 290deg, #1b070d, #800f2f, #ff758f, #2e0c16, #1b070d)',
    core: '#ff758f',
    glow: 'rgba(128,15,47,.35)',
    rotate: '-22deg'
  },
  {
    id: 'track-pt-2',
    title: 'The Girl From Ipanema',
    artist: 'Frank Sinatra & Antônio Carlos Jobim',
    language: 'Portuguese / English',
    languageCode: 'pt-BR',
    meta: 'BOSSA NOVA · 1967 · SUN-DRENCHED SHORE',
    youtubeId: 'QBmPMIZ1gq8',
    lore: 'Written at the Veloso bar overlooking the sands of Rio by Tom Jobim and Vinicius de Moraes, defining the breezy, swaying elegance of bossa nova for the world.',
    artistBackground: 'Antônio Carlos Jobim was the legendary architect of bossa nova whose sophisticated jazz harmonies reshaped 20th-century global music.',
    timeSuitability: ['daylight', 'golden-hour'],
    art: 'radial-gradient(circle at 68% 28%, #fefae0 0 9%, transparent 27%), radial-gradient(ellipse at 35% 65%, #dda15e 0 15%, transparent 47%), conic-gradient(from 45deg, #1e1b13, #bc6c25, #dda15e, #3a321d, #1e1b13)',
    core: '#dda15e',
    glow: 'rgba(188,108,37,.32)',
    rotate: '18deg'
  },

  // ── BENGALI INDIE ───────────────────────────────────────────────────────
  {
    id: 'track-bn-1',
    title: 'Amake Amar Moto',
    artist: 'Anupam Roy',
    language: 'Bengali',
    languageCode: 'bn-IN',
    meta: 'BENGALI INDIE · 2010 · EXISTENTIAL RAIN',
    youtubeId: 'vYsfSlEBh5Y',
    lore: 'Composed on an acoustic guitar while looking out at the Kolkata rain, asking the world to let one live on their own quiet terms without judgment.',
    artistBackground: 'Anupam Roy single-handedly sparked a modern renaissance in Bengali independent and cinema music with his philosophical, poetic songwriting.',
    timeSuitability: ['morning', 'daylight', 'after-dark'],
    art: 'radial-gradient(circle at 45% 35%, #e9ecef 0 8%, transparent 25%), radial-gradient(ellipse at 55% 65%, #495057 0 16%, transparent 48%), conic-gradient(from 200deg, #121416, #343a40, #adb5bd, #1c2024, #121416)',
    core: '#adb5bd',
    glow: 'rgba(73,80,87,.3)',
    rotate: '-15deg'
  },

  // ── ITALIAN INDIE ───────────────────────────────────────────────────────
  {
    id: 'track-it-1',
    title: 'Paracetamolo',
    artist: 'Calcutta',
    language: 'Italian',
    languageCode: 'it-IT',
    meta: 'ITALIAN INDIE · 2018 · ROMAN DAYDREAM',
    youtubeId: 'UW1DjnCBcSY',
    lore: 'Combines witty, unconventional lyrics about feverish infatuation with lush vintage synth melodies, evoking summer evenings riding a Vespa through Rome.',
    artistBackground: 'Edoardo D’Erme, known as Calcutta, revolutionized the modern Italian indie-pop scene with his infectious hooks and surreal, poetic lyricism.',
    timeSuitability: ['daylight', 'golden-hour'],
    art: 'radial-gradient(circle at 65% 30%, #ffdfba 0 8%, transparent 26%), radial-gradient(ellipse at 35% 65%, #ff6b6b 0 15%, transparent 48%), conic-gradient(from 110deg, #2b1212, #c92a2a, #ffa8a8, #3b1717, #2b1212)',
    core: '#ffa8a8',
    glow: 'rgba(201,42,42,.32)',
    rotate: '20deg'
  },

  // ── ARABIC ALT-INDIE ────────────────────────────────────────────────────
  {
    id: 'track-ar-1',
    title: 'Shim El Yasmine',
    artist: 'Mashrou\' Leila',
    language: 'Arabic',
    languageCode: 'ar-LB',
    meta: 'ARABIC INDIE · 2009 · BEIRUT LULLABY',
    youtubeId: 'Mczl-lyU_LY',
    lore: 'An acoustic confession written by Hamed Sinno with delicate violin and guitar, singing tenderly about domestic intimacy, smelling jasmine, and fragile love.',
    artistBackground: 'Formed in Beirut at the American University, Mashrou’ Leila became a revolutionary voice in modern Arab independent alternative music.',
    timeSuitability: ['evening', 'after-dark'],
    art: 'radial-gradient(circle at 45% 38%, #f8f9fa 0 7%, transparent 24%), radial-gradient(ellipse at 58% 64%, #6c757d 0 15%, transparent 46%), conic-gradient(from 320deg, #15171a, #495057, #ced4da, #1f2227, #15171a)',
    core: '#ced4da',
    glow: 'rgba(108,117,125,.3)',
    rotate: '-10deg'
  },

  // ── TURKISH PSYCH / ANATOLIAN ───────────────────────────────────────────
  {
    id: 'track-tr-1',
    title: 'Goca Dünya',
    artist: 'Altın Gün',
    language: 'Turkish',
    languageCode: 'tr-TR',
    meta: 'ANATOLIAN PSYCH · 2018 · BOSPHORUS GROOVE',
    youtubeId: 'FyQ_5uLyFMo',
    lore: 'A reimagining of Erkin Koray’s classic Turkish psych-folk song, fusing electric bağlama saz riffs with funk basslines and disco synthesizers.',
    artistBackground: 'Grammy-nominated band Altın Gün brilliantly revives 1970s Turkish psychedelic rock with modern dancefloor energy and hypnotic grooves.',
    timeSuitability: ['daylight', 'golden-hour'],
    art: 'radial-gradient(circle at 55% 35%, #ffd166 0 8%, transparent 26%), radial-gradient(ellipse at 42% 65%, #ef476f 0 16%, transparent 48%), conic-gradient(from 70deg, #26111a, #b01a47, #f78c6b, #381523, #26111a)',
    core: '#f78c6b',
    glow: 'rgba(239,71,111,.35)',
    rotate: '16deg'
  },

  // ── NEO-SOUL & SUNSET R&B ───────────────────────────────────────────────
  {
    id: 'track-en-6',
    title: 'Texas Sun',
    artist: 'Khruangbin & Leon Bridges',
    language: 'English',
    languageCode: 'en-US',
    meta: 'TEXAS NEO-SOUL · 2020 · GOLDEN DRIVE',
    youtubeId: 'Whe7MURlKLw',
    lore: 'Conceived on the backroads of Texas, uniting Khruangbin’s hypnotic reverb-drenched basslines with Leon Bridges’ velvety, vintage southern soul vocals.',
    artistBackground: 'Houston trio Khruangbin and Fort Worth soul icon Leon Bridges teamed up to craft a sun-soaked love letter to desolate desert highways.',
    timeSuitability: ['daylight', 'golden-hour'],
    art: 'radial-gradient(circle at 62% 28%, #ffb703 0 9%, transparent 28%), radial-gradient(ellipse at 38% 65%, #fb8500 0 16%, transparent 48%), conic-gradient(from 125deg, #211504, #995200, #ffb703, #382408, #211504)',
    core: '#ffb703',
    glow: 'rgba(251,133,0,.35)',
    rotate: '22deg'
  },
  {
    id: 'track-en-7',
    title: 'Japanese Denim',
    artist: 'Daniel Caesar',
    language: 'English',
    languageCode: 'en-US',
    meta: 'R&B / NEO-SOUL · 2016 · SLOW BURN',
    youtubeId: 'cbBSTPjOMOA',
    lore: 'Written about enduring love that only grows richer with age like high-grade raw denim, carried by a slow-walking bassline and rich gospel organ chords.',
    artistBackground: 'Grammy-winning Toronto R&B singer Daniel Caesar is celebrated for his timeless gospel chord progressions and warm, vulnerable falsetto.',
    timeSuitability: ['evening', 'after-dark'],
    art: 'radial-gradient(circle at 45% 35%, #caf0f8 0 7%, transparent 23%), radial-gradient(ellipse at 55% 65%, #03045e 0 16%, transparent 48%), conic-gradient(from 240deg, #07091d, #023e8a, #48cae4, #0f1538, #07091d)',
    core: '#48cae4',
    glow: 'rgba(2,62,138,.34)',
    rotate: '-14deg'
  }
];
